name: Deploy to GitHub Pages

on:
  push:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci
      - name: Build (Static Generate)
        run: |
          echo "NITRO_PRESET=github-pages" >> $GITHUB_ENV
          echo "NUXT_PUBLIC_DIRECT_API=true" >> $GITHUB_ENV
          echo "NUXT_PUBLIC_BASE_URL=/${{ github.event.repository.name }}/" >> $GITHUB_ENV
          npx nuxi generate
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .output/public
      - name: Deploy to Pages
        uses: actions/deploy-pages@v4
